import "../assets/scss/globals.scss";
import Header from "@/components/header";
import { TransactionProvider } from "@/context/transactionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TransactionProvider>
          <Header />
          {children}
        </TransactionProvider>
      </body>
    </html>
  );
}
